name: README build

on:
  push:
    branches:
      - main
  schedule:
    - cron: '30 1 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Get Python 3.8                               
        uses: actions/setup-python@v2                               
        with:                                 
          python-version: '3.8'
      - name: Get dateutil
        run: pip install python-dateutil
      - name: Update README file
        run: python today.py
      - name: Commit
        run: |-
          git add .
          git diff
          git config --global user.email "github-action-bot@example.com"
          git config --global user.name "GitHub Action Bot"
          git commit -m "Updated README" -a || echo "No changes to commit"
          git push
